Bump base64 dependency to 0.21.0
parallaxsecond/parsec pull request #679
Opened 2023-06-20 08:37 UTC by ema

2023-06-20 15:50 UTC, tgonzalezorlandoarm commented
Formatting error to fix :)

2023-07-20 10:02 UTC, ionut-arm approved these changes

2023-08-21 11:01 UTC, tgonzalezorlandoarm requested changes

2023-08-21 11:01 UTC, tgonzalezorlandoarm commented on src/key_info_managers/on_disk_manager/mod.rs
> +    match base64::engine::general_purpose::URL_SAFE_NO_PAD.decode(base64_bytes) {
engine::general_purpose::URL_SAFE.decode(base64_bytes) ?

2023-09-11 13:25 UTC, tgonzalezorlandoarm submitted a review, later dismissed
LGTM

2023-09-26 12:29 UTC, tgonzalezorlandoarm commented
e2e_tests should have the neccesary changes as well :)

2023-09-27 12:18 UTC, tgonzalezorlandoarm commented
`Cargo.lock` seems to be corrupt.
If you want to update base64 to version 0.21.0, my suggestion is to run:
```
git reset --soft HEAD^
git restore --staged Cargo.lock
cargo update --package base64@0.21.2 --precise 0.21.0
git add Cargo.lock
```
And commit again

2023-09-28 09:18 UTC, tgonzalezorlandoarm approved these changes

2023-09-28 09:18 UTC, tgonzalezorlandoarm commented
LGTM Thanks!

2023-09-28 10:02 UTC, merged